# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Al Ehsaan
email: AlEhsan2024@gmail.com
phone: +1-781-532-1530
description: >- # this means to ignore newlines until "baseurl:"
  Al Ehsaan Muslim Network is a modest beginning with the hope and motivation to become 
  a multifaceted organization providing needed support to Muslims in the New England 
  community, in sha Allah.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: AlamZaki
# github_username:  zalam003

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-geocode
#  - jekyll-maps # https://ayastreb.me/jekyll-maps/

# Geocode
jekyll_geocode:
  file-name: members.yml # Name of the YML store inside _data with a list of datas (required)
  file-path: _data # Path of the YML file, folder of your data (_data) by default (optional)
  name: name # Name of the field from the YML that will gave the name of the generated file (the name will be downcase and space replace by a dash) (required)
  address: address # Name of the address (street + city) or only street field (if city field exists) from the YML (required)
  postcode: postcode # Postcode from the YML (optional)
  city: city # Name of the town field from the YML, if you have a separated field address and city (optional)
  region: region # Name of the region, county or state or all in the same field from the YML (optional)
  country: country # Name of the country from the YML (optional)
  cache: true # Test if a file already exist
  outputfile: place.yml # Give the name of the file for an yml output (otherwise it will be JSON) <= usefull for jekyll-map

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
